---
- name: Install apache
  yum:
   name: "{{ apache_pkg }}"
   state: "{{ pkg_state }}"


- name: Start Daemon
  service:
   name: "{{ service_name }}"
   state: "{{ service_state }}"


- name: Create a file
  file:
   path: "{{ file_path }}"
   state: "{{ file_state }}"
   mode: "{{ file_mode }}"


- name: File Content
  lineinfile:
    path: "{{ file_path }}"
    line: "{{ file_content }}"
