---
- hosts: all
  become: True
  #become_user: root
  ignore_errors: 1
  gather_facts: yes

  tasks: 
    - name: Create a file
      file:
        path: /tmp/playbookfile
        mode: '0400'
        state: touch
      tags:
        - file

    - name: Check something
      command: jkhgtrg
      tags:
        - cmd
      

    - name: Create a Directory
      file: 
        path: /tmp/dir
        mode: '0700'
        state: directory
      tags:
        - dir

    - name: Create a Group
      group: 
        name: security
        state: present

    - name: Create user called Robert
      user:
        name: Robert
        comment: Robert TEMTA
        group: security
      when: ansible_os_family == "Debian" or ansible_processor_nproc > 2

    - name: Check server Uptime
      command: uptime
    
    - name: Check the Date
      shell: cat /etc/passwd | grep Robert
      