---
- name: Jjinaja template
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
     - vars.yml
    

  tasks:
    - name: Copy config file
      template:
          dest: /tmp/apache.config
          src: /home/ec2-user/Ansible-dev/apache.j2